//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace SkillIT.Properties {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resources {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resources() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("SkillIT.Properties.Resources", typeof(Resources).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to locate the number of applicants for this job.
        /// </summary>
        internal static string Applicant_Count_Missing {
            get {
                return ResourceManager.GetString("Applicant_Count_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to There was nothing found to extract. This may be due to a bug. Please contact the application owner..
        /// </summary>
        internal static string Dump_Error_Description {
            get {
                return ResourceManager.GetString("Dump_Error_Description", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Extraction Error.
        /// </summary>
        internal static string Dump_Error_Title {
            get {
                return ResourceManager.GetString("Dump_Error_Title", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to login, please verify credentials and url.
        /// </summary>
        internal static string Login_Failure {
            get {
                return ResourceManager.GetString("Login_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No jobs were able to be located based on this search.
        /// </summary>
        internal static string No_Jobs_Found_Search_Response {
            get {
                return ResourceManager.GetString("No_Jobs_Found_Search_Response", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Unable to refresh the login status, please login again.
        /// </summary>
        internal static string Refresh_Login_Failure {
            get {
                return ResourceManager.GetString("Refresh_Login_Failure", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to No information to save.
        /// </summary>
        internal static string Save_Extract_Missing {
            get {
                return ResourceManager.GetString("Save_Extract_Missing", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized resource of type System.Drawing.Icon similar to (Icon).
        /// </summary>
        internal static System.Drawing.Icon SkillITLogo {
            get {
                object obj = ResourceManager.GetObject("SkillITLogo", resourceCulture);
                return ((System.Drawing.Icon)(obj));
            }
        }
    }
}
